### PR TITLE
Add CircleCI tests :-)

### LINKED ISSUE #7: Test on CircleCI ?
hello,

would you be interested in a PR to run on CircleCI (similar to Travis, see how it looks like at https://circleci.com/gh/marco-m/etaoin) ?

### PR DESCRIPTION
**Pull request by marco-m**
Fixes #7, see https://circleci.com/gh/marco-m/ghostwheel

TODO BEFORE MERGING By @gnl :

- create project on circleci, login with github
- enable building for PR
- update README.adoc to point to the correct ghostwheel on circleci :-)

### CODE REVIEW

**Comment by marco-m** [comment]
mmhh wait, I just saw the package.json file. I never touched npm, am I supposed to use this file with nmp, so that I get specific versions ? I was following the instructions on the karma web site and I was wondering how I could specify versions ...

**Comment by gnl** [comment]
If you have a `package.json` file, just running `npm install` in the project directory will install the packages and versions specified in it, so that will probably be the simplest way to handle this.

**Comment by marco-m** [comment]
OK, I now use `npm install`, see the results at https://circleci.com/gh/marco-m/ghostwheel/13. On my side this PR is ready to go.

Note on the other hand that I still have to do also `sudo npm install -g karma-cli`, otherwise the tests don't find the `karma` executable. Is maybe `karma-cli` missing from package.json ?

**Comment by gnl** [comment]
This is looking good, thanks! And regarding the npm thing – `karma-cli` has to be installed globally with `npm -g` so that the executable is on the path and `package.json` is only used for local dependencies installed into the project's own `node_modules` directory.

**Pull request merged**
